#![no_std]
// agent-policy (Task M2-V1b). §13.4 easy-case probe: cross-contract read of GovVault from a
// NORMAL entrypoint (not auth). SOURCE: stellar-accounts (git v0.8.0-rc.1, soroban-sdk 26.0.0)
// + §foundation §2.3.
//
// NOTE (M2-V1a divergence): the OZ crate is depended on via a git pin (v0.8.0-rc.1) because the
// *published* crates.io stellar-accounts 0.7.1 targets soroban-sdk 25.3.x, which is incompatible
// with our 26.0.0 workspace. See workspace Cargo.toml comment for the full empirical finding.
use gov_vault::GovVaultClient; // generated by #[contractimpl] in gov-vault (built as rlib).
use soroban_sdk::{contract, contractimpl, Address, Env};

#[cfg(test)]
mod test;

#[contract]
pub struct AgentPolicy;

#[contractimpl]
impl AgentPolicy {
    /// §13.4 EASY-CASE probe: cross-contract read of GovVault from a NORMAL entrypoint (not auth).
    /// M1 already proves normal cross-reads work; this just wires the client. The HARD case
    /// (cross-read inside `enforce` during auth) is Task M2-V1c.
    pub fn probe_cross_read(env: Env, gov_vault: Address, id: u32) -> bool {
        GovVaultClient::new(&env, &gov_vault).is_approved(&id)
    }
}
