// Barrel for the generated `stellar contract bindings typescript` output (foundation §1).
// Consumers import the typed contract clients via `@shadowkit/shared/bindings`:
//   import { GovVault } from "@shadowkit/shared/bindings";
//   const client = new GovVault.Client({ ... });
// The generated module re-exports all of `@stellar/stellar-sdk` (`export * from ...`), so each
// contract is re-exported under its OWN namespace to avoid name collisions between contracts and
// to keep the SDK re-exports out of the top-level `@shadowkit/shared/bindings` surface.
// REGENERATED by `scripts/deploy-local.sh` after each gov-vault deploy — do not hand-edit the
// generated files under ./<contract>/.
export * as GovVault from "./gov-vault/src/index.js";
